### ISSUE TITLE
Remove blockquotes from dataview query columns 

### ISSUE THREAD

**Issue by johans3** [efemkay/obsidian-modular-css-layout#15]
Greater than ">" is reserved for _blockquotes_, so whenever i create a callout with `[!blank-container]` to nest _dataview queries_, the result will be a blockquote in **preview mode**. 

Of course i don't need blockquotes in **preview mode**, i just want to _group dv queries_ and secondly i use a custom css to render blockquotes, so your callout isn't placed anymore at the center of my note and this gets even messier if i place 2 dataview callouts one next another

I didn't try yet, but your css should be able to render callouts without _blockquotes_ in **preview mode**

**Comment by efemkay** [comment]
hi there. sorry took me awhile to respond coz i was a bit confused by your statement. the syntax for standard callout does use blockquote for it to be detected as such, and as far as i understand the rationale by obsidian dev is so that it will fallback to normal blockquotes when not used in obsidian

my snippet just provide a custom callout (via css formatting, no js/ts code). 

#### here example of ways you can put dv in callout, u still need at least the first dv code to be inside "`>`"
![image](https://user-images.githubusercontent.com/42369515/177259578-6b184cc4-3746-4b8f-839c-d0a30976a441.png)

#### reference on obsidian callout syntax
![image](https://user-images.githubusercontent.com/42369515/177258888-082b2be6-a164-4630-9999-6d7d89c777fd.png)
