### ISSUE TITLE
Unable to Use Width-Control

### ISSUE THREAD

**Issue by kennygokh** [efemkay/obsidian-modular-css-layout#18]
Hi, I am not able to see or use the width-control setting. The code below did not have any differences after applying the width control. Please advise.

>[!multi-column]
>>[!todo|wide-2]+ Overdue
>>
>>```tasks
>>not done
>>due before today
>>sort by due
>>```
>
>>[!todo|wide-4]+ Due Today
>>```tasks
>>not done
>>due today
>>sort by due
>>```
>
>>[!todo|wide-2]+ Due Tomorrow
>>```tasks
>>not done
>>due tomorrow
>>sort by due
>>```

**Comment by efemkay** [comment]
My [!multi-column] comes with minimum width for sub callout (200px by default, can be changed via Style Settings). The minimum width is to allow content to look good on mobile (making sub-callout flow to next row rather than squeezed). Btw, that minimum width will sort prevent the width control using `wide-x` when note width is not wide or there are many sub-callout.

So to override that, use the `min-0` i include with v.0.4.0. so your markdown should look like below. Let me know if this solves it for you.

```markdown
> [!multi-column]
>
>> [!todo|wide-2 min-0]+ Overdue
>> 
>> ```tasks
>> not done
>> due before today
>> sort by due
>> ```
>
>> [!todo|wide-4 min-0]+ Due Today
>> 
>> ```tasks
>> not done
>> due today
>> sort by due
>> ```
>
>> [!todo|wide-2 min-0]+ Due Tomorrow
>> 
>> ```tasks
>> not done
>> due tomorrow
>> sort by due
>> ```
```

**Comment by kennygokh** [comment]
Thanks @efemka. Just realised that I have not been updated the latest css. It is working fine now 🙏
