### ISSUE TITLE
Showcase-Request

### ISSUE THREAD

**Issue by Volker-brdb** [efemkay/obsidian-modular-css-layout#4]
Hi efemkay,

I would really appreceate to see in your Showcases how the md-file looks like for the design which can be seen in "multi-column-showcase.png" in your screenshot folder.
Thx

**Comment by efemkay** [comment]
hi. well, i'm not quite "done" with it yet. partly becoz i need to explain that you need _Markdown Attributes_ plugin for the multi column list (at block level) to work and i also wanted to replace with actual example rather than placeholder text. anyway, here's the md file (as it is now).
[Multi Column Showcase 2.md](https://github.com/efemkay/obsidian-modular-css-layout/files/8561679/Multi.Column.Showcase.2.md)

**Comment by Volker-brdb** [comment]
Thank you 👍
