### ISSUE TITLE
List Column first column a little bit lower

### ISSUE THREAD

**Issue by how2051** [efemkay/obsidian-modular-css-layout#64]
when I write a list column using tag `#mcl/list-column`, the first column seems to be a little bit lower than the following column, for example:

```
- ### Example #mcl/list-column
	- xxxxx
	- xxxxx
	- xxxxx
- ### Example
	- xxxxx
	- xxxxx
	- xxxxx
- ### Example
	- xxxxx
	- xxxxx
	- xxxxx
```

![column list](https://github.com/efemkay/obsidian-modular-css-layout/assets/55384174/d4fd4922-5bab-4dd5-9a6c-13d0a97cd8b7)

**Comment by how2051** [comment]
FYI, other list wont have this issue.

![other list](https://github.com/efemkay/obsidian-modular-css-layout/assets/55384174/eb160f4a-f3e2-46dc-8afa-1bfe4818de7d)

**Comment by how2051** [comment]
FYI, other list wont have this issue:

![other list](https://github.com/efemkay/obsidian-modular-css-layout/assets/55384174/3063ed32-637b-4904-be59-dc38b71b5903)

**Comment by efemkay** [comment]
hey there. sorry for delayed response. when i design List Column i don't think it would be used with headers in list like your example. but for List Grid and List Card that's pretty much sth i expected (use with headers in list).

that said, the remedy is simple enough (which is as per additional code snippet below). however, i'm not planning to implement it for the time being because i'm trying to optimise the MCL performance and excessive usage of CSS `:has()` does impact the overall performance. if you need in your case, do add the snippet below in your personal css file.

```css
/* remove ul margin top when the first li is a heading */
div > ul:has(> li > [data-heading] > [href*="#mcl/list-column"]) {
    margin-top: 0;
}
```

**Comment by how2051** [comment]
Thank you so much for telling me the detail and solution  :)
